/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GameMapInterface extends Interface {
  getFunction(
    nameOrSignature: "claimTile" | "getTileOwner" | "worldTiles"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TileClaimed"): EventFragment;

  encodeFunctionData(
    functionFragment: "claimTile",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTileOwner",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "worldTiles",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "claimTile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTileOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "worldTiles", data: BytesLike): Result;
}

export namespace TileClaimedEvent {
  export type InputTuple = [
    worldId: BigNumberish,
    x: BigNumberish,
    y: BigNumberish,
    newOwner: AddressLike
  ];
  export type OutputTuple = [
    worldId: bigint,
    x: bigint,
    y: bigint,
    newOwner: string
  ];
  export interface OutputObject {
    worldId: bigint;
    x: bigint;
    y: bigint;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameMap extends BaseContract {
  connect(runner?: ContractRunner | null): GameMap;
  waitForDeployment(): Promise<this>;

  interface: GameMapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimTile: TypedContractMethod<
    [worldId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTileOwner: TypedContractMethod<
    [worldId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [string],
    "view"
  >;

  worldTiles: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [[string, bigint] & { owner: string; tileType: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimTile"
  ): TypedContractMethod<
    [worldId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTileOwner"
  ): TypedContractMethod<
    [worldId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "worldTiles"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [[string, bigint] & { owner: string; tileType: bigint }],
    "view"
  >;

  getEvent(
    key: "TileClaimed"
  ): TypedContractEvent<
    TileClaimedEvent.InputTuple,
    TileClaimedEvent.OutputTuple,
    TileClaimedEvent.OutputObject
  >;

  filters: {
    "TileClaimed(uint256,uint256,uint256,address)": TypedContractEvent<
      TileClaimedEvent.InputTuple,
      TileClaimedEvent.OutputTuple,
      TileClaimedEvent.OutputObject
    >;
    TileClaimed: TypedContractEvent<
      TileClaimedEvent.InputTuple,
      TileClaimedEvent.OutputTuple,
      TileClaimedEvent.OutputObject
    >;
  };
}
