/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameMap } from "./GameMap";
export * as factories from "./factories";
export { GameMap__factory } from "./factories/GameMap__factory";
