/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { GameMap, GameMapInterface } from "../GameMap";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "worldId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "TileClaimed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "worldId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    name: "claimTile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "worldId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    name: "getTileOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "worldTiles",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "tileType",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102628061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80630a6215ae146100465780637675a3e51461009c578063b8a32c7e14610102575b600080fd5b61007f610054366004610200565b600092835260208381526040808520938552928152828420918452529020546001600160a01b031690565b6040516001600160a01b0390911681526020015b60405180910390f35b6100e16100aa366004610200565b600060208181529381526040808220855292815282812090935282529020546001600160a01b03811690600160a01b900460ff1682565b604080516001600160a01b03909316835260ff909116602083015201610093565b610115610110366004610200565b610117565b005b60008381526020818152604080832085845282528083208484529091529020546001600160a01b0316156101895760405162461bcd60e51b8152602060048201526015602482015274151a5b19481a5cc8185b1c9958591e481bdddb9959605a1b604482015260640160405180910390fd5b60008381526020818152604080832085845282528083208484528252918290208054336001600160a01b03199091168117909155825185815291820184905281830152905184917fa2a6aa11b3e307a3a2d16bed2bb47047a2e5a2301bf7d76bbeab835e9ec1b1cd919081900360600190a2505050565b60008060006060848603121561021557600080fd5b50508135936020830135935060409092013591905056fea2646970667358221220a92c994dc7e70871080fe5384a71ca143a815019fea807a4db2b0df71ad3017664736f6c634300081c0033";

type GameMapConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GameMapConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GameMap__factory extends ContractFactory {
  constructor(...args: GameMapConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GameMap & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GameMap__factory {
    return super.connect(runner) as GameMap__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GameMapInterface {
    return new Interface(_abi) as GameMapInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): GameMap {
    return new Contract(address, _abi, runner) as unknown as GameMap;
  }
}
