/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { GameMap, GameMapInterface } from "../GameMap";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "TileClaimed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    name: "claimTile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "tiles",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "tileType",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101df8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80635019d3ea1461003b5780638a3d7cdc14610050575b600080fd5b61004e610049366004610187565b6100b2565b005b61008d61005e366004610187565b60006020818152928152604080822090935290815220546001600160a01b03811690600160a01b900460ff1682565b604080516001600160a01b03909316835260ff90911660208301520160405180910390f35b6000828152602081815260408083208484529091529020546001600160a01b03161561011c5760405162461bcd60e51b8152602060048201526015602482015274151a5b19481a5cc8185b1c9958591e481bdddb9959605a1b604482015260640160405180910390fd5b6000828152602081815260408083208484528252918290208054336001600160a01b0319909116811790915582518581529182018490528183015290517f67126f5f1d63521282c9181a7e603e66131149b94a100e31046b45a1fb74b5a29181900360600190a15050565b6000806040838503121561019a57600080fd5b5050803592602090910135915056fea26469706673582212209fef8eef266e8420602fad9facc3b3cd31fea224dc45530713f177d69a0bd5b164736f6c634300081c0033";

type GameMapConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GameMapConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GameMap__factory extends ContractFactory {
  constructor(...args: GameMapConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GameMap & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GameMap__factory {
    return super.connect(runner) as GameMap__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GameMapInterface {
    return new Interface(_abi) as GameMapInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): GameMap {
    return new Contract(address, _abi, runner) as unknown as GameMap;
  }
}
